### ISSUE TITLE
Download Failure

### ISSUE THREAD

**Issue by abadgerw** [PennHui2016/OpDEA#1]
@PennHui2016 I read with interest your fantastic paper. I have tried to download the R package with the instructions provided and received the following error:

Downloading GitHub repo PennHui2016/OpDEA@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  :
  download from 'https://api.github.com/repos/PennHui2016/OpDEA/tarball/HEAD' failed

Any insight into what may be going on? 

I would just run the .bat file but I'm using a Mac unfortunately.

**Comment by PennHui2016** [comment]
I have never tried to install my R package on a Mac machine. But it works on windows machines, can you use another machine instead, sorry for the inconvenience

**Comment by abadgerw** [comment]
I was ultimately able to get the package downloaded using the .tar file here on GitHub.
